# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Kazuaki/Desktop/ov7670/ov7670.cache/wt [current_project]
set_property parent.project_path C:/Users/Kazuaki/Desktop/ov7670/ov7670.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files C:/Users/Kazuaki/Desktop/ov7670/mem.coe
add_files -quiet c:/Users/Kazuaki/Desktop/ov7670/ov7670.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files c:/Users/Kazuaki/Desktop/ov7670/ov7670.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/Kazuaki/Desktop/ov7670/ov7670.srcs/sources_1/new/SRAM.v
  C:/Users/Kazuaki/Desktop/ov7670/ov7670.srcs/sources_1/new/sccb_rom.v
  C:/Users/Kazuaki/Desktop/ov7670/ov7670.srcs/sources_1/new/VGA_CTRL.v
  C:/Users/Kazuaki/Desktop/ov7670/ov7670.srcs/sources_1/new/CAM_CTRL.v
  C:/Users/Kazuaki/Desktop/ov7670/ov7670.srcs/sources_1/new/LINEIN_CTRL.v
  C:/Users/Kazuaki/Desktop/ov7670/ov7670.srcs/sources_1/new/sccb_if.v
  C:/Users/Kazuaki/Desktop/ov7670/ov7670.srcs/sources_1/new/VideoProcCore.v
  C:/Users/Kazuaki/Desktop/ov7670/ov7670.srcs/sources_1/new/VideoProc.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Kazuaki/Desktop/ov7670/ov7670.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files C:/Users/Kazuaki/Desktop/ov7670/ov7670.srcs/constrs_1/new/pin.xdc]


synth_design -top VideoProc -part xc7z010clg400-1


write_checkpoint -force -noxdef VideoProc.dcp

catch { report_utilization -file VideoProc_utilization_synth.rpt -pb VideoProc_utilization_synth.pb }
